version: 0.1.0-{build}
image: ubuntu
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOCKER_USERNAME:
    secure: bDPKwqVjooeu2YoztZ0QJy698lawFCmIn7jMQKOkrEo=
  DOCKER_PASSWORD:
    secure: rNVSLt9bSh6feHbxoZ2VuA==
init:
  - git config --global core.autocrlf true
install:
  - ps: .\.psscripts\install-dotnet.ps1
build: off
build_script:
  - ps: .\build.ps1
test: off
nuget:
  account_feed: false
  project_feed: false