version: 3.0.2.{build}
os:
  - Visual Studio 2015
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  # Force MSBuild 14
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - nuget restore
build:
  publish_wap: true
  verbosity: normal
deploy:
  provider: WebDeploy
  skip_symbols: false
  server: https://ci-buildstats.scm.azurewebsites.net:443/msdeploy.axd?site=ci-buildstats
  website: ci-buildstats
  username: $ci-buildstats
  password:
    secure: dNuktJi2zyNFdPUvEKzOSvVb4ltb5PVMzdrFEh4IjfFr5keN3OHFkGj4WKM5/aG1y3VrWOEe3FUxWLPBgeTaBw==
  remove_files: true
  app_offline: false
  on:
    branch: master
    appveyor_repo_tag: true