version: 3.6.1.{build}
os:
  - Visual Studio 2015
configuration: Release
platform: Any CPU
skip_tags: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - nuget restore
build:
  publish_wap: true
  verbosity: normal
deploy:
  provider: WebDeploy
  skip_symbols: false
  server: https://buildstats.scm.azurewebsites.net:443/msdeploy.axd?site=buildstats
  website: buildstats
  username: $buildstats
  password:
    secure: izO3e9FoIB/Rt8Cn72Ypc11tqSe1NnjHYwt70SXvCiuLdAayHKdZvi8GEHURZ0V+mHaknDYkSHK6RwHRibWKgQ==
  remove_files: true
  app_offline: false
  skip_dirs: '\\App_Data'
  on:
    branch: master